### ISSUE TITLE
Scenarios

### ISSUE THREAD

**Issue by dimitri-rusin** [dimitri-rusin/oll_onemax#14]
- lambdas: discrete action space [1, 2, 3, 4, 5, 6, 7, 8] VERSUS [2, 4, 6, 7, 8] VERSUS - lambdas: continuous action space: 1 - 8.
- DDQN versus PPO
- gap_to_optimality: 0.95 VERSUS 0.8 VERSUS 0.7 VERSUS 0.6 VERSUS 0.5

**Comment by ndangtt** [comment]
1. Problem sizes: 
- 500, 1000, 2000, 3000
- [optional] 10, 50, 100, 200

2. Action space: 
- Discrete: 
    - 100: [1, 10, 40, 60]
    - 1000: [x, x, x, x]
    - 3000: [x, x, x, x]
- Continuous: [1..n]

3. Initial solution:
- random 
- [optional] 80%, 95%


4. RL algorithm:
- DDQN (sb3, discrete action space)
- PPO (sb3, discrete & cont action space)
- [optional] Ray


**Next steps:**
- Fill in the holes: talk with Carola
- Define a default hyper-parameter setting for DDQN & PPO
- Define an RL training budget (for each problem size?)
- Launch experiments

**Comment by dimitri-rusin** [comment]
This is the experiment setting that's currently being evaluated with 10 random seeds, each at most for 7 hours, on Cirrus.

These are some general parameters:
```
dimensionality: 80
lambdas: [1, 2, 4, 8, 16, 32]
num_evaluation_episodes: 150
num_timesteps_per_evaluation: 400
closeness_to_optimum: 0.5
reward_type: EVALUATIONS_PLUS_FITNESS
state_type: ONE_HOT_ENCODED
num_environments: 16
max_training_timesteps: 2_000_000
```

These are PPO-specific parameters:
```
ppo:
  batch_size: 64
  clip_range: 0.2
  device: auto
  ent_coef: 0.0
  gae_lambda: 0.95
  gamma: 0.99
  learning_rate: 0.0003
  max_grad_norm: 0.5
  n_epochs: 10
  n_steps: 2_048
  policy: MlpPolicy
  sde_sample_freq: -1
  stats_window_size: 100
  verbose: 0
  vf_coef: 0.5
```
